sudo: false
language: node_js
node_js:
  - '0.10'
cache:
  directories:
    - node_modules
    - bower_components
after_script:
  - npm run coveralls
notifications:
  flowdock:
    secure: k4IsldQFwgTCdDwU/JGWNsK+ngMVFz7tvxX5SPLT5TqhZY6QWWkRkv/BL+0xka3mylOh0O+6xDydWb2qKEaT466STEx+OC2sCoEzl+fF5JJyWm+nKrW9u9y/AGkjJCBylYnjDPmyE5+5DEImYVfDuWtGVgGdSj4y+/P8ZX4Z5gk=
before_deploy:
  - ./travis/build.sh
deploy:
  provider: s3
  access_key_id: AKIAJHBUIN7T5C5BML2Q
  secret_access_key:
    secure: VMiWVya4zfyabg9dCr6eYwKx1RDKBdE0KN9CJnYJtLO0k8elM+yWwu7Nq1TyrXtJz/oFVcIMCqkw/+cRr38HYrVLsYUOYDYhJM9FsJQi4vITR/pBWfgL21cK6rTQU7LXF6XmhokazT9xp22Sb1q6SSWtfR1PyNlsjDg918ePNTE=
  bucket: dev-dd-ehealth-org-ng
  region: eu-west-1
  local-dir: dist
  skip_cleanup: true
  on:
    repo: eHealthAfrica/direct-delivery-dashboard
    branch: develop
